// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hscarzgjltsdronamltt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzY2FyemdqbHRzZHJvbmFtbHR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNzkwMDksImV4cCI6MjA4NTk1NTAwOX0.4RYONU3KtlOk6xVpIj8CWSYNVJdp0JOOGPNHcCOeOUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});